server:
  port: 8093
  tomcat:
    max-connections: 2000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crossoverjie?characterEncoding=utf-8&rewriteBatchedStatements=true&&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    database: 0

  rabbitmq:
    host: 49.234.28.122
    port: 5672
    username: guest
    password: guest

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath:/xml/*.xml
